name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: bivex
          theme: dark
          format: svg
          output: dist/streak-stats.svg

      - name: Generate Contribution Snake
        run: |
          mkdir -p dist
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://github-readme-stats.vercel.app/api?username=bivex&show_icons=true&theme=tokyonight&hide_border=true" \
               -o dist/github-stats.svg

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
